### ISSUE TITLE
configuration files need more documentation

### ISSUE THREAD

**Issue by bryantChhun** [czbiohub/microDL#134]
it's not clear what any of the fields in the configuration .yml files do.

For example, for config_preprocess, what is the relationship between `tile: depths`, `tile: mask-depth`, `channel_ids` and `masks: channels`?

Additionally, each step of the process (`generate_meta`, `preprocess` etc... ) produces files or folders, but it's not clear what those are and for what purpose

**Comment by smguo** [comment]
duplicated as #127. Closing
