### ISSUE TITLE
Branch "Infer_on_large_image": shape mismatch errors when input image dimension is not power of 2

### ISSUE THREAD

**Issue by smguo** [czbiohub/microDL#37]
proposed fix: add a cropping block in read_one
`def _read_one(tp_dir, channel_ids, fname, flat_field_dir=None):
        """Read one image set

        :param str tp_dir: timepoint dir
        :param list channel_ids: list of channels to read from
        :param str fname: fname of the image. Expects the fname to be the same
         in all channels
        :param str flat_field_dir: dir where flat field images are stored
        :returns: np.array of shape nb_channels, im_size (with or without
         flat field correction)
        """

        cur_images = []
        for ch in channel_ids:
            cur_fname = os.path.join(tp_dir,
                                     'channel_{}'.format(ch),
                                     fname)
            cur_image = np.load(cur_fname).astype(np.float32)
            if flat_field_dir is not None:
                ff_fname = os.path.join(flat_field_dir,
                                        'flat-field_channel-{}.npy'.format(ch))
                ff_image = np.load(ff_fname)
                cur_image = image_utils.apply_flat_field_correction(
                    cur_image, flat_field_image=ff_image)
            cur_image = zscore(cur_image)
          ## minimally crop the image from center to have cropped shape always power of 2
            image_shape = np.asarray(cur_image.shape)
            crop_shape = 2**(np.floor(np.log2(image_shape))-1)
            crop_shape = crop_shape.astype(np.int)            
            ctr = np.floor(image_shape/2).astype(np.int)
            cur_image =  cur_image[ctr[0]-crop_shape[0]:ctr[0]+crop_shape[0],
                                   ctr[1]-crop_shape[1]:ctr[1]+crop_shape[1]]
            
            cur_images.append(cur_image)
        cur_images = np.stack(cur_images)
        return cur_images`

**Comment by jennyfolkesson** [comment]
This is fixed with image_inference.py
