### ISSUE TITLE
[master branch] "tile_image" generate tiles with different sizes when the input image dimension is not the multiple of input tile size

### ISSUE THREAD

**Issue by smguo** [czbiohub/microDL#41]
proposed fix:
change 
`for row in range(0, n_rows, step_size[0]):
        if row + tile_size[0] > n_rows:
            row = check_in_range(row, n_rows, tile_size[0])
        for col in range(0, n_cols, step_size[1]):
            if col + tile_size[1] > n_cols:
                col = check_in_range(col, n_cols, tile_size[1])`
to 
`for row in range(0, n_rows - tile_size[0] + step_size[0]+ 1, step_size[0]):
        if row + tile_size[0] > n_rows:
            row = check_in_range(row, n_rows, tile_size[0])
        for col in range(0, n_cols - tile_size[1] + step_size[1]+ 1, step_size[1]):
            if col + tile_size[1] > n_cols:
                col = check_in_range(col, n_cols, tile_size[1])`

**Comment by jennyfolkesson** [comment]
This issue is fixed in master. But it is a major refactor so it might not work to rebase to your branch.

**Comment by smguo** [comment]
Thanks Jenny! I saw the if statement has been fixed, but I think the range for the row and column indices need to be fixed too, otherwise the function will generate the last tile multiple times as long as row < n_rows-step_size[0]

**Comment by jennyfolkesson** [comment]
Ah yes, you're right. I'll submit a PR soon.

**Comment by jennyfolkesson** [comment]
Solved by #42
