### ISSUE TITLE
find optimal # of z-slices for image translation (2.5D label-free -> 2D fluorescence)

### ISSUE THREAD

**Issue by mattersoflight** [czbiohub/microDL#67]
What is the optimal receptor field along the z dimension for virtual staining? It should be similar to the receptor field along XY, because biological structures are not aligned in cartesian coordinates. However, optical resolution along Z is 2x lower than XY resolution.
 
The accuracy of prediction may improve when information outside optical resolution limit is used. 
Imaging is typically done with 5x5 pixels within the XY resolution limit of microscope and 5 slices within the Z resolution limit.

**Comment by jennyfolkesson** [comment]
Tested z = 3, 5, 7. There was improvement in test metrics going from 3 to 5, but not from 5 to 7 so we settled on z = 5 as the optimal number of slices for 2.5D models.
